#  simple travis ci file
language: python

python:
  - "3.5"

sudo: required
  
install:
  - pip install requests
  
script:
  - python3 setup.py install
  - python3 tests/procedure/test_upgrade_code.py
  - python3 tests/test_capt.py
