#  simple travis ci file
language: python

python:
  - "3.5"

# sudo: required

before_install:


install:
   - pip install -r requirements.txt
   - python setup.py install
  
script:
   - python -m unittest discover -s tests
