#  simple travis ci file
language: generic

python:
  - "3.5"

sudo: required

# https://github.com/travis-ci/travis-ci/issues/5326
# modules fail to import
before_install:
#   - python setup.py install
#   - echo $PATH
#   - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
#   - echo $PATH
#   - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
  
#install:
   - pip3 install urllib3
   - pip3 install requests
   - pip3 install argcomplete
  
script:
#   - echo $PATH
   - python -m unittest discover -s tests
#   - python -m unittest test_capt.py
